apiVersion: v1
data:
  access-token: ZG9wX3YxXzAyZjkzZjAyN2QxNWI3ZTg3NzIxNDU5ZjE4ZWE5NjBmNmMwOWE2ODRkNmVhNWY4ODk3MDZiYTljMmYzZGQyMzk=
kind: Secret
metadata:
  creationTimestamp: null
  name: do-token
