apiVersion: v1
data:
  access-token: ZG9wX3YxX2IyYzEyZWM4OGE2NWI0NjU5ZjY0MTAwODdkMGRmNTRkZDFkNzhkYzk3ZmI5N2NlMDdlMzc0YTQwNTkzOThjNDQ=
kind: Secret
metadata:
  creationTimestamp: null
  name: do-token
